### ISSUE TITLE
Treasury fraction of distributed rewards not accurately described in monetary policy

### ISSUE THREAD

**Issue by TrevorBenson** [input-output-hk/cardano-documentation#512]
For a span of over 200 epochs there has been far greater than 20% going into the treasury from the reserves. The documentation would lead one to believe that 80% of the per epoch reserves of ADA that is being minted would be going to the delegators and operators of the network. This is not the case and the documentation glosses over this reality. 

1. The content from this documentation page eludes to **τ (funds going into the Treasury)** as being 20%. However review of [Treasury, Circulation, Reserves and Rewards Allocations](https://docs.google.com/spreadsheets/d/1xny1W7HhHANLNeQcnbr8El5rakJ80VIM7fgDwJ-uqys) shows that this is actually greater than 30%.  

2. The following [Compound contribution to the Treasury from
the inefficiencies of the pools](https://forum.cardano.org/uploads/short-url/lTWNaaAvpqavd2W4u23laCrHjnY.pdf) explains the compounding effect of inefficiencies, leading to much greater than 20% moving to the treasury.
   * The findings list 40% going to treasury from the per epoch reserves.
     * During epochs 213-223 the treasury exceeded 40%, and on occasion even 50%, averaging 43.2% of the per epoch reserves
     * During epochs 224-240 the treasury averaged 34.4% of the per epoch reserves
     * During epochs 241-388 the treasury averaged 31% of the per epoch reserves

An average of 31% is going into the Treasury per epoch for over 150 epochs. This in essence is either: 
* A reduction of the delegator fraction of rewards by 13.75%, conversely would increase rewards by > 15% per epoch.
* A depletion of the reserves by an additional amount which goes to the treasury instead of being retained in the reserves. 

The documentation does not address this and that seems like being disingenuous or intentionally withholding or obfuscating the truth from the participants. I suggest the documentation should explain the parameters setting of 20%. However it should strive to describe accurately the split the treasury actually receives per epoch, because it is clearly not 20% and has a real impact on the bottom line of the delegators compounded annual return on stake and the operators profit margins, or the length of time reserves will be available before the network needs to be fully self sustaining.

**Comment by feqifei** [comment]
Hi Trevor, thanks for your work. 
This issue was discussed here https://forum.cardano.org/t/double-treasury-taxation-of-40-and-possible-workarounds/41461 on the end of 2020.
The discussion generated a proposal, through a pre-CIP, to decrease rewards that flow to Treasury to an effective 20% on distributed rewards instead of the whole reward pot, but due to the lack of interest among both IOG and the Cardano community it was finally retired. The result is that around 40% of the reserve will sooner or later flow into the Treasury.

https://github.com/cardano-foundation/CIPs/pull/35/files

**Comment by TrevorBenson** [comment]
Hey @feqifei, thank you for the initial work and PDF. I'm familiar with the CIP (ie. PR #35). Without commitment to fix the issue you brought up I'm now hoping for a minimum of documentation clarification.

However, I'd also like to suggest reconsidering opening the CIP and seeing if we can gain consensus on the changes. I believe I actually recall when this was only worked on, the part of the community I recall debating the fix was catalyst participants who felt they didn't want the treasuries cut adjusted, although I did not agree with this viewpoint. I don't recall if others at the time voiced similar opinions, but I may have missed Twitter or other threads of discussion.

 I feel the research that went into the p and t parameters should not be in vain. I don't feel accepting the resulting extra treasury funds due to inefficiencies should be the path forward, even if some disagree. If the CIP is not reopened I definitely invite your view of how this could be easily described in the documentation. I read your PDF and the forum threads, again, yesterday before opening the ticket. I was going to take another pass today before coming up with a suggested change for the docs. I suspect with your efforts and deep knowledge of the topic you may have a very succinct idea of what should change. However I will definitely advocate for the CIP if you are willing to reopen it for discussion, as I personally support it and wish I had been vocal in the past at trying to gather more support for it.

Thanks

**Comment by feqifei** [comment]
Hi Trevor, the lesson my friends and I have learnt at that time is that it's a lost battle trying to change the protocol behavior if the people/organizations that have the power of taking the decision are the same that benefit of the current situation.
And I don't mean that those people/organizations are acting with bad intentions, not at all.
The thing is that I come from a country where government taxation rate on people and businesses is around 50% overall and those funds are so bad managed.
Watching at the Treasury taking almost 40% of Cardano reserves, officially for the "common good" of the community, is something that is hard to agree on from my viewpoint. 
Moreover, most of community members think that only 20% go to the Treasury because there is no clarity at all.
Anyway, and I speak for myself only, after that experience I prefer not to be involved again in a process that at that time wasted several days and energy.
Maybe thank to CIP-1694 something could change in the future.
I think that your request of just more clarity in the official documentation is fair and maybe achievable and I'll fully support you

**Comment by olgahryniuk** [comment]
Hello @TrevorBenson & @feqifei ! Thank you for raising this issue, we'll address it to update the documentation.

**Comment by olgahryniuk** [comment]
We discussed this issue with Kevin Hammond, IOG's Head of Software Engineering. The treasury rate explanation has been updated to explain the observed difference in percentage. 
If calculating actual rewards rather than the monetary expansion, you might get a higher percentage (up to 30%). Also, it's important to note that the rewards given to stake pools may be reduced under certain conditions, such as when pools are not saturated, not fully pledged, or fail to produce their allocated blocks. Any unclaimed rewards remain in the reserves for future allocation. This clarifies the observed difference.
